version: '3.1'
services:
  mysql:
    restart: always
    image: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
      - ./log:/var/log/mysql

  nacos-gateway:
    restart: always
    image: tea-shop/nacos-gateway:latest
    ports:
      - 8090:8090
    volumes:
      - ./data/log/nacos-gateway:/var/log/nacos-gateway

  shop-goods:
    restart: always
    image: tea-shop/shop-goods:latest
    ports:
      - 9091:9091
    volumes:
      - ./var/log/shop-goods:/var/log/goods

  shop-customer:
    restart: always
    image: tea-shop/shop-customer:latest
    ports:
      - 9092:9092
    volumes:
      - ./var/log/shop-customer:/var/log/customer

  shop-order:
    restart: always
    image: tea-shop/shop-order:latest
    ports:
      - 9093:9093
    volumes:
     - ./var/log/shop-order:/var/log/order

  shop-files:
    restart: always
    image: tea-shop/shop-files:latest
    ports:
      - 9094:9094
    volumes:
      - ./var/log/shop-files:/var/log/files
      -
  auth:
    restart: always
    image: tea-shop/auth:latest
    ports:
      - 9094:9094
    volumes:
      - ./var/log/auth:/var/log/auth

network:
  default:
    external:
        name: tea-shop