#server:
#  port: 9092
#spring:
#  application:
#    name: shop-customer
#  cloud:
#    # 使用 Nacos 作为服务注册发现
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/tea-shop?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
#    username: root
#    password: Root5683@
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.mapper
#  type-aliases-package: top.lzmvlog.shop.customer.model